namespace ProjectGenerator.Tests.TestData;

// Represents a single test case input and expected output for pipeline tests.
// Used to deserialize test data from JSON files for parameterized tests.
public class TestRequestData
{
    // The project name to use in the test request
    public string ProjectName { get; set; } = "";

    // The page type as a string (e.g., "SinglePage", "MultiPage")
    public string PageType { get; set; } = "";

    // The number of pages to generate
    public int PageCount { get; set; }

    // The expected number of files generated by the pipeline
    public int ExpectedFileCount { get; set; }

    // Whether the test should succeed (true) or fail (false)
    public bool ShouldSucced { get; set; }

    // If failure is expected, the error message should contain this string
    public string ExpectedErrorContains { get; set; } = "";
}